import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const CONTRACTS = ["UnlockConfidentialGovernor", "MockPublicLock"] as const;

const artifactsDir = resolve(__dirname, "../artifacts/contracts");
const sdkAbisDir = resolve(__dirname, "../../sdk/src/abis");

mkdirSync(sdkAbisDir, { recursive: true });

function findArtifact(name: string): string {
  const candidates = [
    resolve(artifactsDir, `${name}.sol/${name}.json`),
    resolve(artifactsDir, `mocks/${name}.sol/${name}.json`),
  ];
  for (const c of candidates) {
    try {
      readFileSync(c);
      return c;
    } catch {
      // try next
    }
  }
  throw new Error(`Artifact not found for ${name}`);
}

const exportLines: string[] = [];

for (const name of CONTRACTS) {
  const artifactPath = findArtifact(name);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown };
  const outPath = resolve(sdkAbisDir, `${name}.ts`);
  const body =
    `// Auto-generated by packages/contracts/scripts/export-abis.ts — do not edit.\n` +
    `export const ${name}ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(outPath, body);
  exportLines.push(`export { ${name}ABI } from "./abis/${name}";`);
  console.log(`wrote ${outPath}`);
}

const barrelPath = resolve(__dirname, "../../sdk/src/abis.ts");
writeFileSync(
  barrelPath,
  `// Auto-generated by packages/contracts/scripts/export-abis.ts — do not edit.\n` + exportLines.join("\n") + "\n",
);
console.log(`wrote ${barrelPath}`);
