import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const CONTRACTS = ["UnlockConfidentialGovernor", "UnlockConfidentialGovernorLiquid", "LiquidDelegation"] as const;

/**
 * External ABIs copied from npm packages into the SDK. We emit them with
 * `as const` so viem gets full type inference at call sites — a plain JSON
 * import degrades to `unknown` return types.
 *
 * When an entry sets `addressKey`, the deployment artifact's `address` is
 * also merged into `packages/sdk/src/addresses.ts` under the named network
 * + key. ABIs go to `abis/`, addresses go to `addresses.ts` — those files
 * stay strictly typed by purpose.
 */
type ExternalAbi = {
  exportName: string;
  outFile: string;
  artifactPath: string;
  source: string;
  /** Optional: if set, the artifact's `address` is merged into addresses.ts
   *  at `addresses[network][key]`. Only valid for hardhat-deploy artifacts
   *  (which carry both `abi` and `address`). */
  address?: { network: string; key: string };
};

const EXTERNAL_ABIS: readonly ExternalAbi[] = [
  {
    exportName: "PublicLockABI",
    outFile: "PublicLock",
    artifactPath: require.resolve("@unlock-protocol/contracts/dist/abis/PublicLock/PublicLockV15.json"),
    source: "@unlock-protocol/contracts (PublicLockV15)",
  },
  {
    exportName: "NameWrapperABI",
    outFile: "NameWrapper",
    artifactPath: require.resolve("@ensdomains/ens-contracts/deployments/mainnet/NameWrapper.json"),
    source: "@ensdomains/ens-contracts (mainnet deployment)",
    address: { network: "mainnet", key: "nameWrapper" },
  },
  {
    exportName: "PublicResolverABI",
    outFile: "PublicResolver",
    artifactPath: require.resolve("@ensdomains/ens-contracts/deployments/mainnet/PublicResolver.json"),
    source: "@ensdomains/ens-contracts (mainnet deployment)",
    address: { network: "mainnet", key: "publicResolver" },
  },
];

const artifactsDir = resolve(__dirname, "../artifacts/contracts");
const sdkAbisDir = resolve(__dirname, "../../sdk/src/abis");
const sdkAddressesFile = resolve(__dirname, "../../sdk/src/addresses.ts");

mkdirSync(sdkAbisDir, { recursive: true });

function findArtifact(name: string): string {
  const candidates = [
    resolve(artifactsDir, `${name}.sol/${name}.json`),
    resolve(artifactsDir, `mocks/${name}.sol/${name}.json`),
  ];
  for (const c of candidates) {
    try {
      readFileSync(c);
      return c;
    } catch {
      // try next
    }
  }
  throw new Error(`Artifact not found for ${name}`);
}

const exportLines: string[] = [];

for (const name of CONTRACTS) {
  const artifactPath = findArtifact(name);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown };
  const outPath = resolve(sdkAbisDir, `${name}.ts`);
  const body =
    `// Auto-generated by packages/contracts/scripts/export-abis.ts — do not edit.\n` +
    `export const ${name}ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(outPath, body);
  exportLines.push(`export { ${name}ABI } from "./abis/${name}";`);
  console.log(`wrote ${outPath}`);
}

// Collect external addresses while writing ABIs, merge them into the
// canonical `addresses.ts` after all artifacts are processed.
const externalAddresses: Record<string, Record<string, string>> = {};

for (const entry of EXTERNAL_ABIS) {
  const { exportName, outFile, artifactPath, source } = entry;
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as {
    abi: unknown;
    address?: string;
  };
  const outPath = resolve(sdkAbisDir, `${outFile}.ts`);
  const body =
    `// Auto-generated by packages/contracts/scripts/export-abis.ts — do not edit.\n` +
    `// Source: ${source}\n` +
    `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(outPath, body);
  exportLines.push(`export { ${exportName} } from "./abis/${outFile}";`);
  console.log(`wrote ${outPath}`);

  if (entry.address && artifact.address) {
    const { network, key } = entry.address;
    if (!externalAddresses[network]) externalAddresses[network] = {};
    externalAddresses[network][key] = artifact.address;
  }
}

const barrelPath = resolve(__dirname, "../../sdk/src/abis.ts");
writeFileSync(
  barrelPath,
  `// Auto-generated by packages/contracts/scripts/export-abis.ts — do not edit.\n` + exportLines.join("\n") + "\n",
);
console.log(`wrote ${barrelPath}`);

if (Object.keys(externalAddresses).length > 0) {
  syncExternalAddresses(externalAddresses);
}

/**
 * Merges external (npm-sourced) addresses into the same `addresses.ts` that
 * the deploy scripts also write to. Both writers share the same {networkKey:
 * Record<string, string>} shape and preserve each other's entries via a
 * scoped-eval read of the file's existing object literal.
 */
function syncExternalAddresses(updates: Record<string, Record<string, string>>) {
  const existing = readExistingAddresses();
  const merged: Record<string, Record<string, string>> = { ...existing };
  for (const [network, entries] of Object.entries(updates)) {
    merged[network] = { ...(merged[network] ?? {}), ...entries };
  }

  const formatted = Object.entries(merged)
    .map(([name, addrs]) => {
      const fields = Object.entries(addrs)
        .map(([k, v]) => `    ${k}: "${v}",`)
        .join("\n");
      return `  ${name}: {\n${fields}\n  },`;
    })
    .join("\n");

  const output =
    `// Auto-generated by packages/contracts deploy hooks + export-abis.ts.\n` +
    `// Manual edits are overwritten on the next deploy or compile.\n\n` +
    `export const addresses = {\n${formatted}\n} as const;\n\n` +
    `export type NetworkName = keyof typeof addresses;\n`;

  writeFileSync(sdkAddressesFile, output);
  console.log(`merged external addresses → ${sdkAddressesFile}`);
}

function readExistingAddresses(): Record<string, Record<string, string>> {
  if (!existsSync(sdkAddressesFile)) return {};
  try {
    const text = readFileSync(sdkAddressesFile, "utf8");
    const match = text.match(/export const addresses = (\{[\s\S]*?\}) as const;/);
    if (!match) return {};

    const fn = new Function(`"use strict"; return (${match[1]});`);
    const parsed = fn();
    return parsed && typeof parsed === "object" ? (parsed as Record<string, Record<string, string>>) : {};
  } catch {
    return {};
  }
}
