// Auto-generated by packages/contracts deploy hooks + export-abis.ts.
// Manual edits are overwritten on the next deploy or compile.

export const addresses = {
  sepolia: {
    governor: "0x6Aa59C5Ef399FE82937f69185a26658578CcCDb0",
    lock: "0x03ee8b0e116843810e792ea239ddd212f5139b96",
    liquidDelegation: "0x2Cf952e903A47f9Da647f5E04Cf000D18D670aEA",
    governorLiquid: "0x0Bdf94D63f975D744D4792F5a9d3D6315cc61f83",
  },
  mainnet: {
    nameWrapper: "0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401",
    publicResolver: "0xF29100983E058B709F3D539b0c765937B804AC15",
  },
} as const;

export type NetworkName = keyof typeof addresses;
