// Auto-generated by packages/contracts/deploy/01_governor.ts on deploy.
// Manual edits are overwritten on the next `pnpm run deploy:<network>`.

export const addresses = {
  sepolia: {
    governor: "0x414E3FAaA1BB0E8222b88550bfC6833CD2F2c184",
    lock: "0xfc240d6bfdd13570946dcbb75ff040a035e3c969",
    liquidDelegation: "0xF1A1336119210608a7C6665daF0454F62083D737",
    governorLiquid: "0x4a04bA53E9a95a344eE43814fA031721087CA978",
  },
} as const;

export type NetworkName = keyof typeof addresses;
