// Auto-generated by packages/contracts/deploy/01_governor.ts on deploy.
// Manual edits are overwritten on the next `pnpm run deploy:<network>`.

export const addresses = {
  sepolia: {
    governor: "0xA7B0AB0574F9d7cF3eA31C0e49E6CAA2BB442d27",
    lock: "0x03ee8b0e116843810e792ea239ddd212f5139b96",
    liquidDelegation: "0x8DB9Af5Fe33b605b526F404b38BfDcb36D3F2e98",
    governorLiquid: "0xd8D642E71f361Fb32f0Dd837d5aF8E5eA00b1645",
  },
} as const;

export type NetworkName = keyof typeof addresses;
