// Schemas are the single source of truth in `@ipe-gov/eas` and re-exported
// here so consumers (web app, workers) only need `@ipe-gov/sdk`.
//
// `easContracts` and `schemaUids` below are AUTO-GENERATED by
// `packages/eas/scripts/registerSchemas.ts` on each register run via ts-morph.
// Manual edits to those two declarations are overwritten on the next run.

export * from "@ipe-gov/eas";

export const easContracts = {
  sepolia: {
    chainId: 11155111,
    eas: "0xC2679fBD37d54388Ce493F1DB75320D236e1815e",
    schemaRegistry: "0x0a7E2Ff54e76B8E6659aedc9103FB21c038050D0",
  },
} as const;

export type EasNetworkName = keyof typeof easContracts;

export const schemaUids = {
  sepolia: {
    IpeResident: "0x7b2ad4657a5d1adb2d7c7468ba1187faff0b8f95b94f4ca6627cf8e045d529ca",
    IpeCheckin: "0xf2bd0502d494b2ac56a7d1ad994ccb2cb2f0fd6fd692e10f1af5f25ecb039579",
    IpeRole: "0xdac4e801b13afde4022879ed53dd61f7363921bdf32fc59a85b10b253685b639",
    IpeProjectLaunched: "0x2c2fd8f91080664ca69fcac6063f2fc3d35dc457f593d418b92ee349cb269089",
    IpeSkill: "0x95d4a8afa59a9d8c87ee337e6d66ecf50a354d3fffabca66bd336fdd8dde6435",
  },
} as const;

export type EasUidNetworkName = keyof typeof schemaUids;
export type IpeSchemaUidName = keyof (typeof schemaUids)[EasUidNetworkName];
