// Codegen: read the EAS contract ABI from upstream
// (`@ethereum-attestation-service/eas-contracts`) and write it to
// `src/abi.ts` as a const-asserted TS literal so viem can infer argument
// shapes for `writeContract({ abi, functionName, args })`.
//
// Re-run after upgrading eas-contracts: `pnpm --filter @ipe-gov/eas run export-abi`.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import EAS from "@ethereum-attestation-service/eas-contracts/artifacts/contracts/EAS.sol/EAS.json";

const OUT = resolve(__dirname, "../src/abi.ts");

const header =
  `// Auto-generated by packages/eas/scripts/exportAbi.ts.\n` +
  `// Sourced from @ethereum-attestation-service/eas-contracts.\n` +
  `// Re-run \`pnpm --filter @ipe-gov/eas run export-abi\` after upgrading.\n\n`;

const body = `export const easAbi = ${JSON.stringify(EAS.abi)} as const;\n`;

writeFileSync(OUT, header + body);
execFileSync("pnpm", ["exec", "prettier", "--write", OUT], { stdio: "inherit" });
console.log(`easAbi exported → ${OUT}`);
