/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalsIndexRouteImport } from './routes/proposals.index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as ProposalsNewRouteImport } from './routes/proposals.new'
import { Route as ProposalsProposalIdRouteImport } from './routes/proposals.$proposalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsNewRoute = ProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsProposalIdRoute = ProposalsProposalIdRouteImport.update({
  id: '/proposals/$proposalId',
  path: '/proposals/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/members/': typeof MembersIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/members': typeof MembersIndexRoute
  '/proposals': typeof ProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/members/': typeof MembersIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/members/'
    | '/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/members'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/members/'
    | '/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProposalsProposalIdRoute: typeof ProposalsProposalIdRoute
  ProposalsNewRoute: typeof ProposalsNewRoute
  MembersIndexRoute: typeof MembersIndexRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/new': {
      id: '/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof ProposalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$proposalId': {
      id: '/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof ProposalsProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProposalsProposalIdRoute: ProposalsProposalIdRoute,
  ProposalsNewRoute: ProposalsNewRoute,
  MembersIndexRoute: MembersIndexRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
