import { DeployFunction } from "hardhat-deploy/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { execFileSync } from "node:child_process";
import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Project } from "ts-morph";

type NetworkAddresses = {
  governor: string;
  lock: string;
  liquidDelegation: string;
  governorLiquid: string;
};

// Always write into the workspace SDK so the web app + Cloudflare workers
// (which import `addresses.<network>` at build time) pick up new deployments
// on the next build — no manual copy-paste.
const SDK_ADDRESSES_FILE = resolve(__dirname, "../../sdk/src/addresses.ts");

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  // `FRESH_DELEGATION=1` forces a clean redeploy of the delegation registry +
  // liquid governor. Without this, hardhat-deploy "reuses" the existing
  // artifacts whenever bytecode + args are unchanged (our case), which means
  // `delegateOf[voter][proposalId]` state from the previous governor leaks
  // into the new one. `skipIfAlreadyDeployed: false` alone isn't enough — we
  // have to purge the JSON artifacts so hardhat-deploy doesn't see them.
  if (process.env.FRESH_DELEGATION === "1") {
    const networkDir = resolve(__dirname, `../deployments/${hre.network.name}`);
    for (const name of ["LiquidDelegation", "UnlockConfidentialGovernorLiquid"]) {
      const file = resolve(networkDir, `${name}.json`);
      if (existsSync(file)) {
        unlinkSync(file);
        console.log(`Purged ${name} deployment for fresh redeploy.`);
      }
    }
  }

  let lockAddress = process.env.UNLOCK_PUBLIC_LOCK_ADDRESS;

  if (!lockAddress) {
    const mock = await deploy("MockPublicLock", { from: deployer, log: true });
    lockAddress = mock.address;
    console.log(`No UNLOCK_PUBLIC_LOCK_ADDRESS set; deployed MockPublicLock at ${lockAddress}`);
  }

  const votingPeriod = process.env.VOTING_PERIOD_BLOCKS ?? "7200";

  const governor = await deploy("UnlockConfidentialGovernor", {
    from: deployer,
    args: [lockAddress, votingPeriod],
    log: true,
  });

  console.log(
    `UnlockConfidentialGovernor: ${governor.address} ` + `(lock: ${lockAddress}, votingPeriod: ${votingPeriod} blocks)`,
  );

  // `LiquidDelegation` stores `delegateOf[voter][proposalId]` — keyed on the
  // raw proposalId with no governor identity. Reusing the same registry across
  // governor redeployments causes the new governor's proposalId=N to collide
  // with leftover state from the previous governor's proposalId=N. So we
  // always redeploy the registry alongside the liquid governor, giving each
  // governor a fresh delegation namespace.
  const delegation = await deploy("LiquidDelegation", {
    from: deployer,
    args: [lockAddress],
    log: true,
    skipIfAlreadyDeployed: false,
  });

  console.log(`LiquidDelegation: ${delegation.address} (lock: ${lockAddress})`);

  const governorLiquid = await deploy("UnlockConfidentialGovernorLiquid", {
    from: deployer,
    args: [lockAddress, delegation.address, votingPeriod],
    log: true,
    skipIfAlreadyDeployed: false,
  });

  console.log(
    `UnlockConfidentialGovernorLiquid: ${governorLiquid.address} ` +
      `(lock: ${lockAddress}, delegation: ${delegation.address}, votingPeriod: ${votingPeriod} blocks)`,
  );

  syncSdkAddresses(hre.network.name, {
    governor: governor.address,
    lock: lockAddress,
    liquidDelegation: delegation.address,
    governorLiquid: governorLiquid.address,
  });
};

// Patches the `addresses` declaration in `packages/sdk/src/addresses.ts` via
// the TS AST. Other networks' entries (e.g. hand-maintained ENS addresses
// under `mainnet`) are preserved — only the row for `networkKey` is replaced.
const ADDRESSES_FILE_SEED =
  `// Auto-generated by packages/contracts/deploy/01_governor.ts on deploy.\n` +
  `// Manual edits to the \`addresses\` declaration are overwritten on the next\n` +
  `// \`pnpm run deploy:<network>\`. Other declarations (types, etc.) are\n` +
  `// preserved across runs.\n\n` +
  `export const addresses = {} as const;\n\n` +
  `export type NetworkName = keyof typeof addresses;\n`;

function syncSdkAddresses(networkKey: string, current: NetworkAddresses) {
  if (!existsSync(SDK_ADDRESSES_FILE)) writeFileSync(SDK_ADDRESSES_FILE, ADDRESSES_FILE_SEED);

  const project = new Project({ tsConfigFilePath: undefined });
  const sf = project.addSourceFileAtPath(SDK_ADDRESSES_FILE);
  const decl = sf.getVariableDeclarationOrThrow("addresses");

  const existing =
    readInitializer<Record<string, Record<string, string>>>(decl.getInitializerOrThrow().getText()) ?? {};
  const merged: Record<string, Record<string, string>> = { ...existing, [networkKey]: current };

  decl.setInitializer(`${formatAddresses(merged)} as const`);
  sf.saveSync();

  // ts-morph indents continuation lines to the initializer column. Run
  // prettier afterward to normalize formatting and keep diffs minimal.
  execFileSync("pnpm", ["exec", "prettier", "--write", SDK_ADDRESSES_FILE], { stdio: "inherit" });

  console.log(`\nSDK addresses synced → ${SDK_ADDRESSES_FILE} (network "${networkKey}")`);
}

function readInitializer<T>(text: string): T | undefined {
  const stripped = text.replace(/\s+as\s+const\s*$/, "");
  try {
    return new Function(`"use strict"; return (${stripped});`)() as T;
  } catch {
    return undefined;
  }
}

function formatAddresses(obj: Record<string, Record<string, string>>): string {
  const entries = Object.entries(obj)
    .map(([net, addrs]) => {
      const fields = Object.entries(addrs)
        .map(([k, v]) => `    ${k}: "${v}",`)
        .join("\n");
      return `  ${net}: {\n${fields}\n  },`;
    })
    .join("\n");
  return `{\n${entries}\n}`;
}

export default func;
func.id = "deploy_unlock_confidential_governor";
func.tags = ["UnlockConfidentialGovernor", "LiquidDelegation", "UnlockConfidentialGovernorLiquid"];
