import { DeployFunction } from "hardhat-deploy/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type NetworkAddresses = {
  governor: string;
  lock: string;
  liquidDelegation: string;
  governorLiquid: string;
};

// Always write into the workspace SDK so the web app + Cloudflare workers
// (which import `addresses.<network>` at build time) pick up new deployments
// on the next build — no manual copy-paste.
const SDK_ADDRESSES_FILE = resolve(__dirname, "../../sdk/src/addresses.ts");

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  // `FRESH_DELEGATION=1` forces a clean redeploy of the delegation registry +
  // liquid governor. Without this, hardhat-deploy "reuses" the existing
  // artifacts whenever bytecode + args are unchanged (our case), which means
  // `delegateOf[voter][proposalId]` state from the previous governor leaks
  // into the new one. `skipIfAlreadyDeployed: false` alone isn't enough — we
  // have to purge the JSON artifacts so hardhat-deploy doesn't see them.
  if (process.env.FRESH_DELEGATION === "1") {
    const networkDir = resolve(__dirname, `../deployments/${hre.network.name}`);
    for (const name of ["LiquidDelegation", "UnlockConfidentialGovernorLiquid"]) {
      const file = resolve(networkDir, `${name}.json`);
      if (existsSync(file)) {
        unlinkSync(file);
        console.log(`Purged ${name} deployment for fresh redeploy.`);
      }
    }
  }

  let lockAddress = process.env.UNLOCK_PUBLIC_LOCK_ADDRESS;

  if (!lockAddress) {
    const mock = await deploy("MockPublicLock", { from: deployer, log: true });
    lockAddress = mock.address;
    console.log(`No UNLOCK_PUBLIC_LOCK_ADDRESS set; deployed MockPublicLock at ${lockAddress}`);
  }

  const votingPeriod = process.env.VOTING_PERIOD_BLOCKS ?? "7200";

  const governor = await deploy("UnlockConfidentialGovernor", {
    from: deployer,
    args: [lockAddress, votingPeriod],
    log: true,
  });

  console.log(
    `UnlockConfidentialGovernor: ${governor.address} ` + `(lock: ${lockAddress}, votingPeriod: ${votingPeriod} blocks)`,
  );

  // `LiquidDelegation` stores `delegateOf[voter][proposalId]` — keyed on the
  // raw proposalId with no governor identity. Reusing the same registry across
  // governor redeployments causes the new governor's proposalId=N to collide
  // with leftover state from the previous governor's proposalId=N. So we
  // always redeploy the registry alongside the liquid governor, giving each
  // governor a fresh delegation namespace.
  const delegation = await deploy("LiquidDelegation", {
    from: deployer,
    args: [lockAddress],
    log: true,
    skipIfAlreadyDeployed: false,
  });

  console.log(`LiquidDelegation: ${delegation.address} (lock: ${lockAddress})`);

  const governorLiquid = await deploy("UnlockConfidentialGovernorLiquid", {
    from: deployer,
    args: [lockAddress, delegation.address, votingPeriod],
    log: true,
    skipIfAlreadyDeployed: false,
  });

  console.log(
    `UnlockConfidentialGovernorLiquid: ${governorLiquid.address} ` +
      `(lock: ${lockAddress}, delegation: ${delegation.address}, votingPeriod: ${votingPeriod} blocks)`,
  );

  syncSdkAddresses(hre.network.name, {
    governor: governor.address,
    lock: lockAddress,
    liquidDelegation: delegation.address,
    governorLiquid: governorLiquid.address,
  });
};

/** Rewrite `packages/sdk/src/addresses.ts`, preserving entries for any
 *  other networks already in the file. Existing entries are merged in via a
 *  scoped eval of the extracted object literal — safe since the file is
 *  controlled by this generator. */
function syncSdkAddresses(networkKey: string, current: NetworkAddresses) {
  const existing = readExistingAddresses();
  const merged: Record<string, NetworkAddresses> = { ...existing, [networkKey]: current };

  const entries = Object.entries(merged)
    .map(([name, addrs]) => {
      const fields = (Object.entries(addrs) as [keyof NetworkAddresses, string][])
        .map(([k, v]) => `    ${k}: "${v}",`)
        .join("\n");
      return `  ${name}: {\n${fields}\n  },`;
    })
    .join("\n");

  const output =
    `// Auto-generated by packages/contracts/deploy/01_governor.ts on deploy.\n` +
    `// Manual edits are overwritten on the next \`pnpm run deploy:<network>\`.\n\n` +
    `export const addresses = {\n${entries}\n} as const;\n\n` +
    `export type NetworkName = keyof typeof addresses;\n`;

  writeFileSync(SDK_ADDRESSES_FILE, output);
  console.log(`\nSDK addresses synced → ${SDK_ADDRESSES_FILE} (network "${networkKey}")`);
}

function readExistingAddresses(): Record<string, NetworkAddresses> {
  try {
    const text = readFileSync(SDK_ADDRESSES_FILE, "utf8");
    const match = text.match(/export const addresses = (\{[\s\S]*?\}) as const;/);
    if (!match) return {};
    // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-new-func
    const fn = new Function(`"use strict"; return (${match[1]});`);
    const parsed = fn();
    if (parsed && typeof parsed === "object") return parsed as Record<string, NetworkAddresses>;
    return {};
  } catch {
    return {};
  }
}

export default func;
func.id = "deploy_unlock_confidential_governor";
func.tags = ["UnlockConfidentialGovernor", "LiquidDelegation", "UnlockConfidentialGovernorLiquid"];
